export enum CacheEnum {
  TIME_ZONE = 'TIME_ZONE',
  CALENDAR_EVENTS = 'CALENDAR_EVENTS',
  BACKGROUND_IMAGES = 'BACKGROUND_IMAGES',
  CREATED_EVENT = 'CREATED_EVENT',
  CALENDAR_HOLIDAY_EVENTS = 'CALENDAR_HOLIDAY_EVENTS',
  CANCEL_EVENT = 'CANCEL_EVENT',
  CUSTOMER_LIST = 'CUSTOMER_LIST',
  CALENDARS = 'CALENDARS',
  HOLIDAY_CALENDARS = 'HOLIDAY_CALENDARS'
}
