export enum TodoItemType {

  WORKER_IMG = 'WORKER_IMG',
  SERVICE_IMG = 'SERVICE_IMG',
  FORM_STYLE = 'FORM_STYLE',
  RESERVATION_BUTTON = 'RESERVATION_BUTTON',
  GOOGLE_CALENDAR_CONNECT = 'GOOGLE_CALENDAR_CONNECT',
  ACCOUNT_UNPAID = 'ACCOUNT_UNPAID',
  NO_SERVICE = 'NO_SERVICE',
  NO_ASSIGN_WORKER_TO_SERVICE = 'NO_ASSIGN_WORKER_TO_SERVICE',
  NO_WORKER = 'NO_WORKER',
  ACCOUNT_EXPIRATION = 'ACCOUNT_EXPIRATION',
  STRIPE_PAYMENT = 'STRIPE_PAYMENT',

  INTEGRATION_GOOGLE_CALENDAR = 'INTEGRATION_GOOGLE_CALENDAR',
  INTEGRATION_GOOGLE_CONTACT = 'INTEGRATION_GOOGLE_CONTACT',
  INTEGRATION_STRIPE = 'INTEGRATION_STRIPE',
  INTEGRATION_TWILIO = 'INTEGRATION_TWILIO',
  INTEGRATION_SMS_MANAGER = 'INTEGRATION_SMS_MANAGER',
  TUTORIAL = 'TUTORIAL',
  TIMEZONE = 'TIMEZONE',
  INVALID_GRANT = 'INVALID_GRANT'

}



// public get todoItemLevel(): typeof TodoItemLevel {
//   return TodoItemLevel;
// }
