export class Error {

  public static FILE_TO_BIG: string = 'FILE_TO_BIG';
  public static UNSUPPORTER_EXTENSION: string = 'UNSUPPORTER_EXTENSION';
  public static GENERAL_ERROR: string = 'GENERAL_ERROR';
  public static DATABASE_ERROR: string = 'DATABASE_ERROR';
  public static EMAIL_ERROR: string = 'EMAIL_ERROR';
  public static MISSING_DATA: string = 'MISSING_DATA';
  public static GOOGLE_CALENDAR_USER_ALREADY_CONNECTED: string = 'GOOGLE_CALENDAR_USER_ALREADY_CONNECTED';
  public static BUSINESS_URL_REQUIRED: string = 'BUSINESS_URL_REQUIRED';
  public static FORGOTTEN_PASSWORD_UNKNOWN_EMAIL: string = 'FORGOTTEN_PASSWORD_UNKNOWN_EMAIL';
  public static FORGOTTEN_PASSWORD_GOOGLE_SIGNUP: string = 'FORGOTTEN_PASSWORD_GOOGLE_SIGNUP';
  public static FORGOTTEN_PASSWORD_FACEBOOK_SIGNUP: string = 'FORGOTTEN_PASSWORD_FACEBOOK_SIGNUP';
  public static RESERVATION_IS_IN_CONFLICT_WITH_ANOTHER_EVENT: string = 'RESERVATION_IS_IN_CONFLICT_WITH_ANOTHER_EVENT';
  public static RESERVATION_IS_IN_CONFLICT_WITH_OPENINGS: string = 'RESERVATION_IS_IN_CONFLICT_WITH_OPENINGS';

}
