export enum Event {
    FIRST = 'FIRST',
    USER_LOADED = 'USER_LOADED',
    LOGOUT = 'LOGOUT',
    LOGIN = 'LOGIN',

    BUSINESSES_LOADED = 'BUSINESSES_LOADED',
    BUSINESS_OR_TEMPLATE_CHANGED = 'BUSINESS_OR_TEMPLATE_CHANGED',

    /**
     * called in the end of the wizard when the user is already login and valid business is created and stored in DB,
     *
     * it is listend by dashboardService to download this business
     */
    WIZARD_FIN = 'WIZARD_FIN',

    BUSINESSES_SAVED = 'BUSINESSES_SAVED',

    RESERVATION_TIME_SELECTED = 'RESERVATION_TIME_SELECTED',
    RESERVATION_WORKER_SELECTED = 'RESERVATION_WORKER_SELECTED',
    RESERVATION_DEVICE_SELECTED = 'RESERVATION_DEVICE_SELECTED',

    DEMO_RESERVATION_TIME_SELECTED = 'DEMO_RESERVATION_TIME_SELECTED',

    GOOGLE_CALENDAR_SUCCESSFULLY_CONNECTED = 'GOOGLE_CALENDAR_SUCCESSFULLY_CONNECTED',

    USER_AFTER_PAYMENT = 'USER_AFTER_PAYMENT',

    LANGUAGE_SWITCH = 'LANGUAGE_SWITCH',
    PAYMENT_FOR_SUBSCRIPTION_SUCCESS = 'PAYMENT_FOR_SUBSCRIPTION_SUCCESS',
    TEMPLATE_LOADED = 'TEMPLATE_LOADED',
    INTEGRATION_UPDATE = 'INTEGRATION_UPDATE',

}
