
export enum NotificationWhenEnum {

  ON_RESERVATION_CREATE = 'ON_RESERVATION_CREATE',
  FIVE_HOURS_BEFORE = 'FIVE_HOURS_BEFORE',
  ONE_DAY_BEFORE = 'ONE_DAY_BEFORE',
  ONE_DAY_AFTER = 'ONE_DAY_AFTER',
  TWO_DAYS_BEFORE = 'TWO_DAYS_BEFORE'

}
